### ISSUE TITLE
Make AbstractProcess start and shutdown failable

### ISSUE THREAD

**Issue by MarkintoshZ** [lunatic-solutions/lunatic-rs#40]
Erlang's gen server allows to start and shutdown process to fail so we should allow such behaviors too.

The current implementation will cause `start` to block forever with the following code
```rust
struct A;

impl AbstractProcess for A {
    type Arg = ();
    type State = A;

    fn init(_: ProcessRef<Self>, _: ()) -> A {
        panic!();
    }
}

A::start((), None);

```

**Comment by bkolobara** [comment]
### `start`

This is a bit tricky for us to do. Wasm doesn't allow stack unwinding and Rust applications compiled to Wasm use `panic=abort`. This means that we can't really catch a panic in the `init` call.

### `shutdown`

According to the docs, Erlang's [`stop(:shutdown)`](https://www.erlang.org/doc/man/gen_server.html#stop-3) can receive a timeout of waiting until it gives up, but it doesn't catch failures?

**Comment by MarkintoshZ** [comment]
Upon further investigation, I realized I had misinterpreted the docs for failure handling. However, Erlang seems to allow `init` to pass back either an `ok` or a `stop`. 
https://github.com/erlang/otp/blob/131398b54cca5f1ae95ed268274936d2efde8c39/lib/stdlib/src/gen_server.erl#L37-L41
Should we implement this? If so, should we have init return a `result<State, String>`?

In addition, would we be concerned about init not terminating or blocks for a very long time? Should we also have a `spawn_timeout` method and/or a spawn-and-forget type of method to handle different use cases?

**Comment by bkolobara** [comment]
> Should we implement this? If so, should we have init return a result<State, String>?

This is also a bit specific in Erlang (from the docs):

> Initialization failed. An exit signal with this Reason (or with reason normal if ignore is returned) is sent to linked processes and ports, notably to the process starting the gen_server when [start_link/3,4 ](https://www.erlang.org/doc/man/gen_server.html#start_link-3)is used.

So basically you can send a specific exit signal back, but the parent can only catch this if the process was linked. I'm not sure what happens in case of using `start` instead of `start_link`? I assume the caller would not be sent anything? Would it block forever?

I'm not sure about this one. If we did implement it, we should go for `Result<State, T>`, but this means we would have an additional generic bound to `AbstractProcess` and it would complicate a bit our signatures and introduce `unwraps` on all `start/_link` calls. I would first maybe love to see if this is actually used much in practice and if someone needs it for a specific use-case we can add it.

We also can't implement this at the moment with signals, because our signals are limited and can't contain arbitrary data.

> In addition, would we be concerned about init not terminating or blocks for a very long time? Should we also have a `spawn_timeout` method and/or a spawn-and-forget type of method to handle different use cases?

I think this is more of a concern to the user. If I remember correctly, Erlang also just documents this (don't block `init` too long or spawn a sub process to finish work so that `init` can return early and not block the caller of `start`). I also prefer to support the minimal amount of features that can cover all use-cases for users and it's up to them to architect specific scenarios. And I think that with the current features you can express this, e.g. `spwan_timeout` would be spawning an `AbstractProcess` where the `init` call spawns a sub-process that does the actual work and sends a message to the main process. The main would then use `receive_timeout` to wait for the initialisation to finish for a specific amount of time.

If we try to cover such specific behaviours we need to make a lot of decisions and the feature set explodes fast. For example, what would you do if the `spawn` function times out? Should you kill the child? Leave it just hanging in the background? What if it was linked, do you want to unlink it? Notice that `spwan_timeout` wouldn't return a reference to the process if the call timed out, so you would not be able to query the process for additional info. It would be hard for us to make all this decisions without overcomplicating everything.

**Comment by MarkintoshZ** [comment]
You are right. I can see how it could be both difficult and undesirable to make the design decisions before we see real-world use cases. It makes a lot of sense just to build out a basic feature set that the user can expand upon based on their own usage.
